/*
 * Problem002.h
 *
 * <<<Insert short description here>>>
 * 	
 * Author: Stanimir Stoykov
 * $Id: $
 *	
 * Copyright (c) 2004-2012 EGT Ltd.
 * All rights reserved
	
 * More information at: http://www.egt-bg.com
 */

#ifndef PROBLEM002_H_
#define PROBLEM002_H_

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * Answer: 4613732
 */
void Problem002()
{
	unsigned long sum = 0;
	unsigned long prev = 1;
	unsigned long next = 1;
	unsigned long newEl = 0;
	while ( next < 4000000 )
	{
		if ( next % 2 == 0 )
			sum += next;

		newEl = prev + next;
		prev = next;
		next = newEl;
	}

	std::cout << sum << std::endl;;
}

#endif /* PROBLEM002_H_ */
